version: '2'
services:
    scriptrepository-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/ScriptRepository/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=ScriptRepository
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
